name: bekgram
description: Bekgram - Telegram + Instagram inspired glassmorphism messenger.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.3.3
  intl: ^0.19.0
  collection: ^1.19.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  socket_io_client: ^3.1.1
  lottie: ^3.3.2
  image_picker: ^1.2.0
  file_picker: ^10.3.2
  record: ^6.1.2
  audioplayers: ^6.5.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - lottie/
